ob-set-targets: Avoid putting non-system go binaries in ~/go

diff --git a/ob-set-targets b/ob-set-targets
--- a/ob-set-targets
+++ b/ob-set-targets
@@ -1,4 +1,5 @@
 #!/bin/sh
+set -e
 
 # To change the versions of ubuntu we target, edit or override the following line
 UBUNTUS="${UBUNTUS:-16.04 18.04}"
@@ -7,9 +8,6 @@ if test -f ci/ob-set-targets.conf
 then
   . ci/ob-set-targets.conf
 fi
-
-# Kludge... where most people put it
-PATH=$HOME/go/bin:$PATH
 
 # A identifier unique to this user and this run
 UNIQ=$$.$LOGNAME
@@ -54,25 +52,33 @@ _EOF_
 }
 
 install_golang() {
-  # Kludge: add go-1.10 to PATH if needed
-  if test -x /usr/lib/go-1.10/bin && ! echo $PATH | grep /usr/lib/go-1.10/bin
-  then
-    PATH=/usr/lib/go-1.10/bin:$PATH
-  fi
-
-  if go version | egrep '1.8|1.9|1.1[0-9]'
-  then
-    return
-  fi
-
   if grep 16.04 /etc/issue
   then
+    export GOPATH=$HOME/go110
+    PATH=$GOPATH/bin:$PATH
+
+    # Kludge: add go-1.10 to PATH if needed
+    if ! echo $PATH | grep /usr/lib/go-1.10/bin
+    then
+      PATH=/usr/lib/go-1.10/bin:$PATH
+    fi
+
+    if go version | egrep "1.10"
+    then
+      return
+    fi
+
+    echo "Warning: installing go-1.10."
     # Default go on ubuntu 16.04 is not sufficient
     sudo add-apt-repository ppa:gophers/archive
     sudo apt update
     sudo apt install -y golang-1.10
   else
-    sudo apt install -y golang
+    PATH=$HOME/go/bin:$PATH
+    if ! go version
+    then
+      sudo apt install -y golang
+    fi
   fi
 }
 
@@ -86,7 +92,7 @@ install_deps() {
   fi
   if ! gitlab-ci-linter --version > /dev/null
   then
-    echo "Can't find gitlab-ci-linter.  Did you add ~/go/bin to PATH?"
+    echo "Can't find gitlab-ci-linter.  Bug..."
     exit 1
   fi
 
@@ -97,7 +103,7 @@ install_deps() {
   fi
   if ! renderizer /dev/null > /dev/null
   then
-    echo "Can't find gitlab-ci-linter.  Did you add ~/go/bin to PATH?"
+    echo "Can't find gitlab-ci-linter.  Bug..."
     exit 1
   fi
 }
